#!/bin/bash

 . ~/.ccio/module/cloudctl/aux/bin/build-cloudctl-profile

lxc init images:fedora/31 cloudctl -p cloudctl
lxc start cloudctl

lxc file push -r ~/.ssh    cloudctl/root/
lxc file push -r ~/.bashrc cloudctl/root/
lxc file push -r ~/.bashrc cloudctl/etc/skel/

lxc exec cloudctl -- /bin/bash -c "groupadd ccio -f --gid $(grep ccio /etc/group | cut -d ':' -f 3)"
lxc exec cloudctl -- /bin/bash -c "usermod -a -G ccio root"

lxc exec cloudctl -- /bin/bash -c "useradd --groups wheel,ccio --create-home ${ministack_UNAME}"
lxc exec cloudctl -- /bin/bash -c "passwd ${ministack_UNAME}"
lxc file push -r ~/.ssh cloudctl/home/${ministack_UNAME}/
lxc exec cloudctl -- /bin/bash -c "chown -R ${ministack_UNAME}:${ministack_UNAME} /home/${ministack_UNAME}/.ssh"

lxc file push /etc/sudoers.d/kmorgan cloudctl/etc/sudoers.d/kmorgan

lxc config device add cloudctl ccio-home disk source=~/.ccio path=/home/${ministack_UNAME}/.ccio

lxc exec cloudctl -- /bin/bash -c "rpm --nodeps --allmatches -e fedora-release-container"
lxc exec cloudctl -- /bin/bash -c "dnf update -y && dnf distrosync -y"
lxc exec cloudctl -- /bin/bash -c "dnf install -y xz jq tar git sudo tmux htop snapd p7zip iperf3 podman skopeo glances buildah hostname neofetch net-tools squashfuse vim-enhanced openssh-server libvirt-client NetworkManager*"
lxc exec cloudctl -- /bin/bash -c "dnf install -y xrdp xorgxrdp xrdp-devel virt-viewer virt-manager xrdp-selinux libvirt-client gnome-tweaks"
lxc exec cloudctl -- /bin/bash -c "dnf group install 'Fedora Workstation' --excludepkg xorg-x11-drv-omap --excludepkg totem-nautilus --excludepkg xorg-x11-drv-armsoc --excludepkg powerpc-utils --excludepkg lsvpd --excludepkg fedora-release-container -y --allowerasing"

lxc exec cloudctl -- /bin/bash -c "systemctl disable systemd-networkd"
lxc exec cloudctl -- /bin/bash -c "systemctl enable --now NetworkManager"
lxc exec cloudctl -- /bin/bash -c "nmcli connection add type ethernet con-name eth0 ifname eth0 ipv4.method auto"
lxc exec cloudctl -- /bin/bash -c "nmcli connection add type ethernet con-name eth1 ifname eth1 ip4 ${ocp_ministack_SUBNET}.3/24 ipv4.dns '8.8.8.8 8.8.4.4'"
lxc exec cloudctl -- /bin/bash -c "nmcli con up eth0"
lxc exec cloudctl -- /bin/bash -c "nmcli con up eth1"

lxc exec cloudctl -- /bin/bash -c "systemctl unmask systemd-logind"
lxc exec cloudctl -- /bin/bash -c "systemctl enable --now sshd"
lxc exec cloudctl -- /bin/bash -c "systemctl enable systemd-logind"
lxc exec cloudctl -- /bin/bash -c "systemctl enable --now sshd"
lxc exec cloudctl -- /bin/bash -c "systemctl enable libvirtd.service"
lxc exec cloudctl -- /bin/bash -c "systemctl enable xrdp.service"
lxc exec cloudctl -- /bin/bash -c "systemctl enable xrdp-sesman.service"
lxc exec cloudctl -- /bin/bash -c "systemctl set-default graphical.target"
lxc exec cloudctl -- /bin/bash -c "systemctl disable firewalld"

lxc exec cloudctl -- /bin/bash -c "virsh net-destroy default"
lxc exec cloudctl -- /bin/bash -c "virsh net-undefine default"
lxc exec cloudctl -- /bin/bash -c "virsh net-list --all"

lxc exec cloudctl -- /bin/bash -c "ln -s /var/lib/snapd/snap /snap"
lxc exec cloudctl -- /bin/bash -c "snap refresh"
lxc exec cloudctl -- /bin/bash -c "snap install snapd"
lxc exec cloudctl -- /bin/bash -c "snap install lxd"

lxc exec cloudctl -- /bin/bash -c "useradd --groups wheel,ccio,kvm,libvirt --create-home ${ministack_UNAME}"

lxc exec cloudctl -- /bin/bash -c "sed -i 's/SELINUX=enforcing/SELINUX=permissive/g' /etc/selinux/config"
lxc exec cloudctl -- /bin/bash -c "update-alternatives --set editor /usr/bin/vim"

lxc exec cloudctl -- /bin/bash -c "shutdown -r now"

ssh ${ministack_UNAME}@$(lxc list -c n,4 --format=csv | awk -F'[, ]' '/eth0/{print $2}')

echo 'alias virsh="virsh -c qemu+ssh://root@${ocp_ministack_SUBNET}.2/system"' >>.bashrc 
lxc remote add msbase ${ocp_ministack_SUBNET}.2
lxc remote switch msbase

#################################################################################
# REFRENCE
#https://stackoverflow.com/questions/59948982/how-to-set-up-guest-vm-spice-client-authentication-with-sasl-qemu-kvm-libvirt
#https://blog.fooock.com/posts/1/manage-virtual-machines-with-libvirt-and-python/
#https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/virtualization_deployment_and_administration_guide/sect-troubleshooting-common_libvirt_errors_and_troubleshooting
#https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/virtualization_host_configuration_and_guest_installation_guide/app_hypervisor_connection_fail
#dd if=/dev/zero of=11GB.dd bs=1024 count=1024000
#sudo timedatectl set-timezone America/Denver
#firewall-cmd --add-port=22/tcp --add-port=3389/tcp --add-service=http/tcp --add-service=https/tcp --permanent
#firewall-cmd --reload
#firewall-cmd --list-ports
#firewall-cmd --state
