---
# Configure All Networks
- name: MSIO | Networking | Libvirt | Install Min2Config Packages
  include: libvirt_install_fedora.yml
  when: ansible_facts['distribution'] == "Fedora" and ansible_facts['distribution_version']|int <= 32
- name: MSIO | Networking | Libvirt | Define Networks
  virt_net:
    command: destroy
    name: default
    state: absent
- name: Define OVS Bridge 'external' from .xml
  virt_net:
    command: define
    name: external
    xml: "{{ lookup('template', lookup('env','HOME') + '/.ccio/ocp-mini-stack/ansible/templates/libvirt/external.xml') }}"
- name: Build Networking Components - Libvirt Networks
  virt_net:
    command: define
    name: default
    xml: "{{ lookup('template', lookup('env','HOME') + '/.ccio/ocp-mini-stack/ansible/templates/libvirt/default.xml') }}"
- name: Define OVS Bridge 'internal' from .xml
  virt_net:
    command: define
    name: internal
    xml: "{{ lookup('template', lookup('env','HOME') + '/.ccio/ocp-mini-stack/ansible/templates/libvirt/internal.xml') }}"
- name: Define OVS Bridge 'ocp' from .xml
  virt_net:
    command: define
    name: ocp-mini-stack
    xml: "{{ lookup('template', lookup('env','HOME') + '/.ccio/ocp-mini-stack/ansible/templates/libvirt/ocp-mini-stack.xml') }}"
- name: Define OVS Bridge 'ocp' from .xml
  virt_net:
    autostart: yes
    name: "{{ item }}"
  with_items:
    - default
    - external
    - internal
    - ocp-mini-stack
- name: Define OVS Bridge 'ocp' from .xml
  virt_net:
    state: active
    name: "{{ item }}"
  with_items:
    - default
    - external
    - internal
    - ocp-mini-stack
